### ISSUE TITLE
Multiple TranslationInputYaml folders

### ISSUE THREAD

**Issue by irbian** [open-sdg/sdg-build#364]
```
translations:
  # This pulls in translations from a Git repository.
  #- class: TranslationInputSdgTranslations
  #  source: https://github.com/open-sdg/sdg-translations.git
  #  tag: master
  # This pulls in translations from a local 'translations' folder.
  - class: TranslationInputYaml
    source: translations
  - class: TranslationInputYaml
    source: generated/translations
```

This won't work. It will ignore the second source, only the first one will work. If I comment the first one, the second one will work properly
